apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-application
          image: nginx:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api-app
