apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpuutilization
      target:
        type: Utilization
        averageUtilization: 40
        periodSeconds: 120